language: python
python:
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install numpy"
  - "pip install scipy"
  - "pip install requests"
  - "pip install astropy"
  - "pip install pandas"
# command to run tests, e.g. python setup.py test
script:
  - cd source
  - python -m tests.test_dbasetools.py
  - python -m tests.test_galextools.py
  - python -m tests.test-gQuery.py
