virtualenv:
  system_site_packages: true
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
#  sudo apt-get install python-scipy
sudo apt-get install build-essential gfortran libatlas-base-dev python-pip python-dev
sudo pip install --upgrade pip
install:
  - pip install numpy
  - pip install scipy
  - pip install requests
  - pip install astropy
  - pip install pandas
# command to run tests, e.g. python setup.py test
script:
  - cd gPhoton
  - nosetests
